export const negativeDecisionStatuses = ['rejected', 'not_awarded', 'exam_failed', 'interview_failed', 'benefits_terminated'];

export const decisionReasonOptions = [
    { value: '', label: 'No reason selected' },
    { value: 'complete_requirements', label: 'Complete requirements' },
    { value: 'missing_documents', label: 'Missing documents' },
    { value: 'academic_requirement_not_met', label: 'Academic requirement not met' },
    { value: 'outside_eligibility', label: 'Outside eligibility' },
    { value: 'passed_prescreening', label: 'Passed pre-screening' },
    { value: 'formal_application_completed', label: 'Formal application completed' },
    { value: 'formal_application_not_completed', label: 'Formal application not completed' },
    { value: 'for_exam', label: 'Meets exam eligibility' },
    { value: 'exam_scheduled', label: 'Exam scheduled' },
    { value: 'exam_completed', label: 'Exam completed' },
    { value: 'passed_exam', label: 'Passed exam' },
    { value: 'failed_exam', label: 'Failed exam' },
    { value: 'for_interview', label: 'For interview' },
    { value: 'failed_interview', label: 'Failed interview' },
    { value: 'passed_interview', label: 'Passed interview' },
    { value: 'qualified_for_formal_application', label: 'Qualified for formal application' },
    { value: 'approved_for_award', label: 'Approved for award' },
    { value: 'distribution_scheduled', label: 'Distribution scheduled' },
    { value: 'award_released', label: 'Reward distributed' },
    { value: 'renewed_support', label: 'Renewed support' },
    { value: 'funds_limited', label: 'Funds limited' },
    { value: 'not_selected', label: 'Not selected' },
    { value: 'procedure_not_followed', label: 'Required procedure not followed' },
    { value: 'recipient_obligations_not_met', label: 'Recipient obligations not met' },
    { value: 'program_conditions_not_met', label: 'Program conditions not met' },
    { value: 'unable_to_contact_recipient', label: 'Unable to contact recipient' },
    { value: 'recipient_requested_end', label: 'Recipient requested to end support' },
    { value: 'other', label: 'Other' },
];
