const fallbackWorkspace = {
    headerDescription: 'Coordinate the request, share files, and review the completed work.',
    headerIcon: 'fa-solid fa-headset',
    meetingTitle: 'Service meeting',
    meetingDescription: 'Choose a preferred time and format for the discussion.',
    meetingPurpose: 'Discuss this provider service request with platform support.',
    filesTitle: 'Files and deliverables',
    filesDescription: 'Share reference files and review work returned by support.',
    providerFilesLabel: 'Files from your team',
    providerFilesEmpty: 'No supporting files uploaded.',
    deliverablesLabel: 'Files from platform support',
    deliverablesEmpty: 'Deliverables will appear here when shared.',
    adminProgressTitle: 'Update progress',
    adminProgressDescription: 'Assign the request, update its status, and mark finished steps.',
};

export const providerServiceWorkspaces = {
    assisted_setup: {
        ...fallbackWorkspace,
        headerDescription: 'Build one clear, complete, and publication-ready scholarship program.',
        headerIcon: 'fa-solid fa-wand-magic-sparkles',
        meetingTitle: 'Setup session',
        meetingDescription: 'Walk through the program, applicant requirements, and publishing questions.',
        meetingPurpose: 'Review the scholarship program setup, requirements, and publishing readiness.',
        filesTitle: 'Program materials',
        filesDescription: 'Share the draft program information and collect the readiness handoff.',
        providerFilesLabel: 'Program drafts and references',
        providerFilesEmpty: 'No program draft or reference has been uploaded.',
        deliverablesLabel: 'Setup notes and readiness review',
        deliverablesEmpty: 'Setup notes and readiness files will appear here.',
        adminProgressTitle: 'Program setup progress',
        adminProgressDescription: 'Track the walkthrough, requirement review, and publishing check.',
    },
    application_cycle_support: {
        ...fallbackWorkspace,
        headerDescription: 'Organize one active application cycle and keep its review work moving.',
        headerIcon: 'fa-solid fa-list-check',
        meetingTitle: 'Cycle planning session',
        meetingDescription: 'Confirm the selected support areas, current blockers, and next operating steps.',
        meetingPurpose: 'Review the active application cycle, selected support areas, and operational blockers.',
        filesTitle: 'Cycle working files',
        filesDescription: 'Share queue or schedule references and review the cycle action plan.',
        providerFilesLabel: 'Cycle references',
        providerFilesEmpty: 'No queue, schedule, or workflow reference has been uploaded.',
        deliverablesLabel: 'Action plan and cycle outputs',
        deliverablesEmpty: 'Cycle recommendations and working outputs will appear here.',
        adminProgressTitle: 'Cycle support progress',
        adminProgressDescription: 'Track the selected operations work and prepare the provider handoff.',
    },
    integration_consultation: {
        ...fallbackWorkspace,
        headerDescription: 'Map the current scholarship process into a practical portal implementation.',
        headerIcon: 'fa-solid fa-diagram-project',
        meetingTitle: 'Discovery session',
        meetingDescription: 'Review the current process, data sources, constraints, and integration goals.',
        meetingPurpose: 'Map the provider current process, data sources, constraints, and portal integration goals.',
        filesTitle: 'Discovery and implementation files',
        filesDescription: 'Share current-process references and collect the recommended implementation path.',
        providerFilesLabel: 'Current process references',
        providerFilesEmpty: 'No process map, form, or data reference has been uploaded.',
        deliverablesLabel: 'Mapping and recommendations',
        deliverablesEmpty: 'Process maps and implementation recommendations will appear here.',
        adminProgressTitle: 'Consultation progress',
        adminProgressDescription: 'Track discovery, workflow mapping, and implementation recommendations.',
    },
};

export function providerServiceWorkspace(planCode) {
    return providerServiceWorkspaces[planCode] ?? fallbackWorkspace;
}
